version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      npm-development:
        dependency-type: development
      npm-production:
        dependency-type: production
    ignore:
      - dependency-name: vite
        versions:
          - 8.x
      - dependency-name: "@vitejs/plugin-react"
        versions:
          - 6.x

  - package-ecosystem: cargo
    directory: /apps/desktop/src-tauri
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
